// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audio.dart';
import 'api/midi.dart';
import 'api/musicxml.dart';
import 'api/score.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -212438465;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_music',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiAudioAllNotesOff();

  void crateApiAudioAudioInit({required String sf2Path});

  String? crateApiMidiConnectedPort();

  Future<Score> crateApiScoreDemoScore();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  List<System> crateApiMusicxmlLayoutSystems({
    required ScoreDocument doc,
    required double availableWidth,
  });

  List<String> crateApiMidiListMidiPorts();

  Stream<MidiEvent> crateApiMidiMidiEventStream();

  void crateApiAudioNoteOff({required int pitch});

  void crateApiAudioNoteOn({required int pitch, required int velocity});

  Future<ScoreDocument> crateApiMusicxmlParseMusicxml({
    required List<int> bytes,
  });

  void crateApiMidiSetMidiPort({String? name});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiAudioAllNotesOff() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioAllNotesOffConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioAllNotesOffConstMeta =>
      const TaskConstMeta(debugName: "all_notes_off", argNames: []);

  @override
  void crateApiAudioAudioInit({required String sf2Path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sf2Path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioAudioInitConstMeta,
        argValues: [sf2Path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioAudioInitConstMeta =>
      const TaskConstMeta(debugName: "audio_init", argNames: ["sf2Path"]);

  @override
  String? crateApiMidiConnectedPort() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMidiConnectedPortConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMidiConnectedPortConstMeta =>
      const TaskConstMeta(debugName: "connected_port", argNames: []);

  @override
  Future<Score> crateApiScoreDemoScore() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_score,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScoreDemoScoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScoreDemoScoreConstMeta =>
      const TaskConstMeta(debugName: "demo_score", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  List<System> crateApiMusicxmlLayoutSystems({
    required ScoreDocument doc,
    required double availableWidth,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_score_document(doc, serializer);
          sse_encode_f_64(availableWidth, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_system,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMusicxmlLayoutSystemsConstMeta,
        argValues: [doc, availableWidth],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicxmlLayoutSystemsConstMeta =>
      const TaskConstMeta(
        debugName: "layout_systems",
        argNames: ["doc", "availableWidth"],
      );

  @override
  List<String> crateApiMidiListMidiPorts() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMidiListMidiPortsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMidiListMidiPortsConstMeta =>
      const TaskConstMeta(debugName: "list_midi_ports", argNames: []);

  @override
  Stream<MidiEvent> crateApiMidiMidiEventStream() {
    final sink = RustStreamSink<MidiEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_midi_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 9,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiMidiMidiEventStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMidiMidiEventStreamConstMeta =>
      const TaskConstMeta(debugName: "midi_event_stream", argNames: ["sink"]);

  @override
  void crateApiAudioNoteOff({required int pitch}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8(pitch, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioNoteOffConstMeta,
        argValues: [pitch],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioNoteOffConstMeta =>
      const TaskConstMeta(debugName: "note_off", argNames: ["pitch"]);

  @override
  void crateApiAudioNoteOn({required int pitch, required int velocity}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8(pitch, serializer);
          sse_encode_u_8(velocity, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioNoteOnConstMeta,
        argValues: [pitch, velocity],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioNoteOnConstMeta => const TaskConstMeta(
    debugName: "note_on",
    argNames: ["pitch", "velocity"],
  );

  @override
  Future<ScoreDocument> crateApiMusicxmlParseMusicxml({
    required List<int> bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_score_document,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiMusicxmlParseMusicxmlConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMusicxmlParseMusicxmlConstMeta =>
      const TaskConstMeta(debugName: "parse_musicxml", argNames: ["bytes"]);

  @override
  void crateApiMidiSetMidiPort({String? name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMidiSetMidiPortConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMidiSetMidiPortConstMeta =>
      const TaskConstMeta(debugName: "set_midi_port", argNames: ["name"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_Char(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return String.fromCharCode(raw);
  }

  @protected
  RustStreamSink<MidiEvent> dco_decode_StreamSink_midi_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Attributes dco_decode_attributes(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Attributes(
      divisions: dco_decode_u_32(arr[0]),
      clefs: dco_decode_list_clef(arr[1]),
      keyFifths: dco_decode_i_32(arr[2]),
      time: dco_decode_time_signature(arr[3]),
    );
  }

  @protected
  BeamState dco_decode_beam_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BeamState.values[raw as int];
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Lyric dco_decode_box_autoadd_lyric(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_lyric(raw);
  }

  @protected
  Pitch dco_decode_box_autoadd_pitch(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pitch(raw);
  }

  @protected
  ScoreDocument dco_decode_box_autoadd_score_document(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_score_document(raw);
  }

  @protected
  StemDir dco_decode_box_autoadd_stem_dir(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_stem_dir(raw);
  }

  @protected
  Tuplet dco_decode_box_autoadd_tuplet(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_tuplet(raw);
  }

  @protected
  Clef dco_decode_clef(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Clef(
      staff: dco_decode_u_32(arr[0]),
      sign: dco_decode_Char(arr[1]),
      line: dco_decode_i_32(arr[2]),
    );
  }

  @protected
  Direction dco_decode_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Direction(
      staff: dco_decode_u_32(arr[0]),
      positionDivisions: dco_decode_u_32(arr[1]),
      kind: dco_decode_direction_kind(arr[2]),
    );
  }

  @protected
  DirectionKind dco_decode_direction_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return DirectionKind_Words(dco_decode_String(raw[1]));
      case 1:
        return DirectionKind_Dynamics(dco_decode_String(raw[1]));
      case 2:
        return DirectionKind_Wedge(
          crescendo: dco_decode_bool(raw[1]),
          stop: dco_decode_bool(raw[2]),
        );
      case 3:
        return DirectionKind_Metronome(
          beatUnit: dco_decode_String(raw[1]),
          perMinute: dco_decode_u_32(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BeamState> dco_decode_list_beam_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_beam_state).toList();
  }

  @protected
  List<Clef> dco_decode_list_clef(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_clef).toList();
  }

  @protected
  List<Direction> dco_decode_list_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_direction).toList();
  }

  @protected
  List<Measure> dco_decode_list_measure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_measure).toList();
  }

  @protected
  List<NotationMeasure> dco_decode_list_notation_measure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_notation_measure).toList();
  }

  @protected
  List<Note> dco_decode_list_note(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_note).toList();
  }

  @protected
  List<NoteEvent> dco_decode_list_note_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_note_event).toList();
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<System> dco_decode_list_system(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_system).toList();
  }

  @protected
  Lyric dco_decode_lyric(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Lyric(
      syllabic: dco_decode_opt_String(arr[0]),
      text: dco_decode_String(arr[1]),
    );
  }

  @protected
  Measure dco_decode_measure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Measure(
      index: dco_decode_u_32(arr[0]),
      notes: dco_decode_list_note(arr[1]),
    );
  }

  @protected
  MidiEvent dco_decode_midi_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MidiEvent(
      kind: dco_decode_midi_event_kind(arr[0]),
      pitch: dco_decode_u_8(arr[1]),
      velocity: dco_decode_u_8(arr[2]),
      timestampMs: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  MidiEventKind dco_decode_midi_event_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MidiEventKind.values[raw as int];
  }

  @protected
  NotationMeasure dco_decode_notation_measure(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return NotationMeasure(
      index: dco_decode_u_32(arr[0]),
      notes: dco_decode_list_note_event(arr[1]),
      directions: dco_decode_list_direction(arr[2]),
      clefs: dco_decode_list_clef(arr[3]),
      minWidth: dco_decode_f_64(arr[4]),
    );
  }

  @protected
  Note dco_decode_note(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Note(
      pitch: dco_decode_u_8(arr[0]),
      startMs: dco_decode_u_64(arr[1]),
      durationMs: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  NoteEvent dco_decode_note_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 18)
      throw Exception('unexpected arr length: expect 18 but see ${arr.length}');
    return NoteEvent(
      staff: dco_decode_u_32(arr[0]),
      voice: dco_decode_u_32(arr[1]),
      positionDivisions: dco_decode_u_32(arr[2]),
      pitch: dco_decode_opt_box_autoadd_pitch(arr[3]),
      isRest: dco_decode_bool(arr[4]),
      isChord: dco_decode_bool(arr[5]),
      durationDivisions: dco_decode_u_32(arr[6]),
      noteType: dco_decode_opt_String(arr[7]),
      dots: dco_decode_u_32(arr[8]),
      accidental: dco_decode_opt_String(arr[9]),
      tieStart: dco_decode_bool(arr[10]),
      tieStop: dco_decode_bool(arr[11]),
      slurStart: dco_decode_bool(arr[12]),
      slurStop: dco_decode_bool(arr[13]),
      tuplet: dco_decode_opt_box_autoadd_tuplet(arr[14]),
      stem: dco_decode_opt_box_autoadd_stem_dir(arr[15]),
      beams: dco_decode_list_beam_state(arr[16]),
      lyric: dco_decode_opt_box_autoadd_lyric(arr[17]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Lyric? dco_decode_opt_box_autoadd_lyric(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_lyric(raw);
  }

  @protected
  Pitch? dco_decode_opt_box_autoadd_pitch(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_pitch(raw);
  }

  @protected
  StemDir? dco_decode_opt_box_autoadd_stem_dir(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_stem_dir(raw);
  }

  @protected
  Tuplet? dco_decode_opt_box_autoadd_tuplet(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_tuplet(raw);
  }

  @protected
  Pitch dco_decode_pitch(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Pitch(
      step: dco_decode_Char(arr[0]),
      octave: dco_decode_i_32(arr[1]),
      alter: dco_decode_i_32(arr[2]),
    );
  }

  @protected
  Score dco_decode_score(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Score(
      bpm: dco_decode_u_32(arr[0]),
      measures: dco_decode_list_measure(arr[1]),
    );
  }

  @protected
  ScoreDocument dco_decode_score_document(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ScoreDocument(
      meta: dco_decode_score_meta(arr[0]),
      staves: dco_decode_u_32(arr[1]),
      attributes: dco_decode_attributes(arr[2]),
      measures: dco_decode_list_notation_measure(arr[3]),
    );
  }

  @protected
  ScoreMeta dco_decode_score_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ScoreMeta(
      title: dco_decode_opt_String(arr[0]),
      composer: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  StemDir dco_decode_stem_dir(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StemDir.values[raw as int];
  }

  @protected
  System dco_decode_system(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return System(
      measures: dco_decode_list_prim_u_32_strict(arr[0]),
      staves: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  TimeSignature dco_decode_time_signature(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TimeSignature(
      beats: dco_decode_u_32(arr[0]),
      beatType: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  Tuplet dco_decode_tuplet(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Tuplet(
      actual: dco_decode_u_32(arr[0]),
      normal: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_Char(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return inner;
  }

  @protected
  RustStreamSink<MidiEvent> sse_decode_StreamSink_midi_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Attributes sse_decode_attributes(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_divisions = sse_decode_u_32(deserializer);
    var var_clefs = sse_decode_list_clef(deserializer);
    var var_keyFifths = sse_decode_i_32(deserializer);
    var var_time = sse_decode_time_signature(deserializer);
    return Attributes(
      divisions: var_divisions,
      clefs: var_clefs,
      keyFifths: var_keyFifths,
      time: var_time,
    );
  }

  @protected
  BeamState sse_decode_beam_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BeamState.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Lyric sse_decode_box_autoadd_lyric(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_lyric(deserializer));
  }

  @protected
  Pitch sse_decode_box_autoadd_pitch(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pitch(deserializer));
  }

  @protected
  ScoreDocument sse_decode_box_autoadd_score_document(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_score_document(deserializer));
  }

  @protected
  StemDir sse_decode_box_autoadd_stem_dir(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_stem_dir(deserializer));
  }

  @protected
  Tuplet sse_decode_box_autoadd_tuplet(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_tuplet(deserializer));
  }

  @protected
  Clef sse_decode_clef(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_staff = sse_decode_u_32(deserializer);
    var var_sign = sse_decode_Char(deserializer);
    var var_line = sse_decode_i_32(deserializer);
    return Clef(staff: var_staff, sign: var_sign, line: var_line);
  }

  @protected
  Direction sse_decode_direction(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_staff = sse_decode_u_32(deserializer);
    var var_positionDivisions = sse_decode_u_32(deserializer);
    var var_kind = sse_decode_direction_kind(deserializer);
    return Direction(
      staff: var_staff,
      positionDivisions: var_positionDivisions,
      kind: var_kind,
    );
  }

  @protected
  DirectionKind sse_decode_direction_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return DirectionKind_Words(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return DirectionKind_Dynamics(var_field0);
      case 2:
        var var_crescendo = sse_decode_bool(deserializer);
        var var_stop = sse_decode_bool(deserializer);
        return DirectionKind_Wedge(crescendo: var_crescendo, stop: var_stop);
      case 3:
        var var_beatUnit = sse_decode_String(deserializer);
        var var_perMinute = sse_decode_u_32(deserializer);
        return DirectionKind_Metronome(
          beatUnit: var_beatUnit,
          perMinute: var_perMinute,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BeamState> sse_decode_list_beam_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BeamState>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_beam_state(deserializer));
    }
    return ans_;
  }

  @protected
  List<Clef> sse_decode_list_clef(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Clef>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_clef(deserializer));
    }
    return ans_;
  }

  @protected
  List<Direction> sse_decode_list_direction(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Direction>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_direction(deserializer));
    }
    return ans_;
  }

  @protected
  List<Measure> sse_decode_list_measure(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Measure>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_measure(deserializer));
    }
    return ans_;
  }

  @protected
  List<NotationMeasure> sse_decode_list_notation_measure(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NotationMeasure>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_notation_measure(deserializer));
    }
    return ans_;
  }

  @protected
  List<Note> sse_decode_list_note(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Note>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_note(deserializer));
    }
    return ans_;
  }

  @protected
  List<NoteEvent> sse_decode_list_note_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NoteEvent>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_note_event(deserializer));
    }
    return ans_;
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<System> sse_decode_list_system(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <System>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_system(deserializer));
    }
    return ans_;
  }

  @protected
  Lyric sse_decode_lyric(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_syllabic = sse_decode_opt_String(deserializer);
    var var_text = sse_decode_String(deserializer);
    return Lyric(syllabic: var_syllabic, text: var_text);
  }

  @protected
  Measure sse_decode_measure(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_32(deserializer);
    var var_notes = sse_decode_list_note(deserializer);
    return Measure(index: var_index, notes: var_notes);
  }

  @protected
  MidiEvent sse_decode_midi_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_midi_event_kind(deserializer);
    var var_pitch = sse_decode_u_8(deserializer);
    var var_velocity = sse_decode_u_8(deserializer);
    var var_timestampMs = sse_decode_u_64(deserializer);
    return MidiEvent(
      kind: var_kind,
      pitch: var_pitch,
      velocity: var_velocity,
      timestampMs: var_timestampMs,
    );
  }

  @protected
  MidiEventKind sse_decode_midi_event_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MidiEventKind.values[inner];
  }

  @protected
  NotationMeasure sse_decode_notation_measure(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_32(deserializer);
    var var_notes = sse_decode_list_note_event(deserializer);
    var var_directions = sse_decode_list_direction(deserializer);
    var var_clefs = sse_decode_list_clef(deserializer);
    var var_minWidth = sse_decode_f_64(deserializer);
    return NotationMeasure(
      index: var_index,
      notes: var_notes,
      directions: var_directions,
      clefs: var_clefs,
      minWidth: var_minWidth,
    );
  }

  @protected
  Note sse_decode_note(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pitch = sse_decode_u_8(deserializer);
    var var_startMs = sse_decode_u_64(deserializer);
    var var_durationMs = sse_decode_u_64(deserializer);
    return Note(
      pitch: var_pitch,
      startMs: var_startMs,
      durationMs: var_durationMs,
    );
  }

  @protected
  NoteEvent sse_decode_note_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_staff = sse_decode_u_32(deserializer);
    var var_voice = sse_decode_u_32(deserializer);
    var var_positionDivisions = sse_decode_u_32(deserializer);
    var var_pitch = sse_decode_opt_box_autoadd_pitch(deserializer);
    var var_isRest = sse_decode_bool(deserializer);
    var var_isChord = sse_decode_bool(deserializer);
    var var_durationDivisions = sse_decode_u_32(deserializer);
    var var_noteType = sse_decode_opt_String(deserializer);
    var var_dots = sse_decode_u_32(deserializer);
    var var_accidental = sse_decode_opt_String(deserializer);
    var var_tieStart = sse_decode_bool(deserializer);
    var var_tieStop = sse_decode_bool(deserializer);
    var var_slurStart = sse_decode_bool(deserializer);
    var var_slurStop = sse_decode_bool(deserializer);
    var var_tuplet = sse_decode_opt_box_autoadd_tuplet(deserializer);
    var var_stem = sse_decode_opt_box_autoadd_stem_dir(deserializer);
    var var_beams = sse_decode_list_beam_state(deserializer);
    var var_lyric = sse_decode_opt_box_autoadd_lyric(deserializer);
    return NoteEvent(
      staff: var_staff,
      voice: var_voice,
      positionDivisions: var_positionDivisions,
      pitch: var_pitch,
      isRest: var_isRest,
      isChord: var_isChord,
      durationDivisions: var_durationDivisions,
      noteType: var_noteType,
      dots: var_dots,
      accidental: var_accidental,
      tieStart: var_tieStart,
      tieStop: var_tieStop,
      slurStart: var_slurStart,
      slurStop: var_slurStop,
      tuplet: var_tuplet,
      stem: var_stem,
      beams: var_beams,
      lyric: var_lyric,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Lyric? sse_decode_opt_box_autoadd_lyric(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_lyric(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Pitch? sse_decode_opt_box_autoadd_pitch(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_pitch(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StemDir? sse_decode_opt_box_autoadd_stem_dir(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_stem_dir(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Tuplet? sse_decode_opt_box_autoadd_tuplet(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_tuplet(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Pitch sse_decode_pitch(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_step = sse_decode_Char(deserializer);
    var var_octave = sse_decode_i_32(deserializer);
    var var_alter = sse_decode_i_32(deserializer);
    return Pitch(step: var_step, octave: var_octave, alter: var_alter);
  }

  @protected
  Score sse_decode_score(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bpm = sse_decode_u_32(deserializer);
    var var_measures = sse_decode_list_measure(deserializer);
    return Score(bpm: var_bpm, measures: var_measures);
  }

  @protected
  ScoreDocument sse_decode_score_document(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_meta = sse_decode_score_meta(deserializer);
    var var_staves = sse_decode_u_32(deserializer);
    var var_attributes = sse_decode_attributes(deserializer);
    var var_measures = sse_decode_list_notation_measure(deserializer);
    return ScoreDocument(
      meta: var_meta,
      staves: var_staves,
      attributes: var_attributes,
      measures: var_measures,
    );
  }

  @protected
  ScoreMeta sse_decode_score_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_opt_String(deserializer);
    var var_composer = sse_decode_opt_String(deserializer);
    return ScoreMeta(title: var_title, composer: var_composer);
  }

  @protected
  StemDir sse_decode_stem_dir(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return StemDir.values[inner];
  }

  @protected
  System sse_decode_system(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_measures = sse_decode_list_prim_u_32_strict(deserializer);
    var var_staves = sse_decode_u_32(deserializer);
    return System(measures: var_measures, staves: var_staves);
  }

  @protected
  TimeSignature sse_decode_time_signature(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_beats = sse_decode_u_32(deserializer);
    var var_beatType = sse_decode_u_32(deserializer);
    return TimeSignature(beats: var_beats, beatType: var_beatType);
  }

  @protected
  Tuplet sse_decode_tuplet(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_actual = sse_decode_u_32(deserializer);
    var var_normal = sse_decode_u_32(deserializer);
    return Tuplet(actual: var_actual, normal: var_normal);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Char(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self, serializer);
  }

  @protected
  void sse_encode_StreamSink_midi_event_Sse(
    RustStreamSink<MidiEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_midi_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_attributes(Attributes self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.divisions, serializer);
    sse_encode_list_clef(self.clefs, serializer);
    sse_encode_i_32(self.keyFifths, serializer);
    sse_encode_time_signature(self.time, serializer);
  }

  @protected
  void sse_encode_beam_state(BeamState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_lyric(Lyric self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_lyric(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_pitch(Pitch self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pitch(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_score_document(
    ScoreDocument self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_score_document(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_stem_dir(StemDir self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_stem_dir(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_tuplet(Tuplet self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_tuplet(self, serializer);
  }

  @protected
  void sse_encode_clef(Clef self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.staff, serializer);
    sse_encode_Char(self.sign, serializer);
    sse_encode_i_32(self.line, serializer);
  }

  @protected
  void sse_encode_direction(Direction self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.staff, serializer);
    sse_encode_u_32(self.positionDivisions, serializer);
    sse_encode_direction_kind(self.kind, serializer);
  }

  @protected
  void sse_encode_direction_kind(DirectionKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case DirectionKind_Words(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case DirectionKind_Dynamics(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case DirectionKind_Wedge(crescendo: final crescendo, stop: final stop):
        sse_encode_i_32(2, serializer);
        sse_encode_bool(crescendo, serializer);
        sse_encode_bool(stop, serializer);
      case DirectionKind_Metronome(
        beatUnit: final beatUnit,
        perMinute: final perMinute,
      ):
        sse_encode_i_32(3, serializer);
        sse_encode_String(beatUnit, serializer);
        sse_encode_u_32(perMinute, serializer);
    }
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_beam_state(
    List<BeamState> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_beam_state(item, serializer);
    }
  }

  @protected
  void sse_encode_list_clef(List<Clef> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_clef(item, serializer);
    }
  }

  @protected
  void sse_encode_list_direction(
    List<Direction> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_direction(item, serializer);
    }
  }

  @protected
  void sse_encode_list_measure(List<Measure> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_measure(item, serializer);
    }
  }

  @protected
  void sse_encode_list_notation_measure(
    List<NotationMeasure> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_notation_measure(item, serializer);
    }
  }

  @protected
  void sse_encode_list_note(List<Note> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_note(item, serializer);
    }
  }

  @protected
  void sse_encode_list_note_event(
    List<NoteEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_note_event(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_system(List<System> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_system(item, serializer);
    }
  }

  @protected
  void sse_encode_lyric(Lyric self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.syllabic, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_measure(Measure self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.index, serializer);
    sse_encode_list_note(self.notes, serializer);
  }

  @protected
  void sse_encode_midi_event(MidiEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_midi_event_kind(self.kind, serializer);
    sse_encode_u_8(self.pitch, serializer);
    sse_encode_u_8(self.velocity, serializer);
    sse_encode_u_64(self.timestampMs, serializer);
  }

  @protected
  void sse_encode_midi_event_kind(
    MidiEventKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_notation_measure(
    NotationMeasure self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.index, serializer);
    sse_encode_list_note_event(self.notes, serializer);
    sse_encode_list_direction(self.directions, serializer);
    sse_encode_list_clef(self.clefs, serializer);
    sse_encode_f_64(self.minWidth, serializer);
  }

  @protected
  void sse_encode_note(Note self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.pitch, serializer);
    sse_encode_u_64(self.startMs, serializer);
    sse_encode_u_64(self.durationMs, serializer);
  }

  @protected
  void sse_encode_note_event(NoteEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.staff, serializer);
    sse_encode_u_32(self.voice, serializer);
    sse_encode_u_32(self.positionDivisions, serializer);
    sse_encode_opt_box_autoadd_pitch(self.pitch, serializer);
    sse_encode_bool(self.isRest, serializer);
    sse_encode_bool(self.isChord, serializer);
    sse_encode_u_32(self.durationDivisions, serializer);
    sse_encode_opt_String(self.noteType, serializer);
    sse_encode_u_32(self.dots, serializer);
    sse_encode_opt_String(self.accidental, serializer);
    sse_encode_bool(self.tieStart, serializer);
    sse_encode_bool(self.tieStop, serializer);
    sse_encode_bool(self.slurStart, serializer);
    sse_encode_bool(self.slurStop, serializer);
    sse_encode_opt_box_autoadd_tuplet(self.tuplet, serializer);
    sse_encode_opt_box_autoadd_stem_dir(self.stem, serializer);
    sse_encode_list_beam_state(self.beams, serializer);
    sse_encode_opt_box_autoadd_lyric(self.lyric, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_lyric(Lyric? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_lyric(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_pitch(Pitch? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_pitch(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_stem_dir(
    StemDir? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_stem_dir(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_tuplet(
    Tuplet? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_tuplet(self, serializer);
    }
  }

  @protected
  void sse_encode_pitch(Pitch self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Char(self.step, serializer);
    sse_encode_i_32(self.octave, serializer);
    sse_encode_i_32(self.alter, serializer);
  }

  @protected
  void sse_encode_score(Score self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.bpm, serializer);
    sse_encode_list_measure(self.measures, serializer);
  }

  @protected
  void sse_encode_score_document(ScoreDocument self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_score_meta(self.meta, serializer);
    sse_encode_u_32(self.staves, serializer);
    sse_encode_attributes(self.attributes, serializer);
    sse_encode_list_notation_measure(self.measures, serializer);
  }

  @protected
  void sse_encode_score_meta(ScoreMeta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.composer, serializer);
  }

  @protected
  void sse_encode_stem_dir(StemDir self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_system(System self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_32_strict(self.measures, serializer);
    sse_encode_u_32(self.staves, serializer);
  }

  @protected
  void sse_encode_time_signature(TimeSignature self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.beats, serializer);
    sse_encode_u_32(self.beatType, serializer);
  }

  @protected
  void sse_encode_tuplet(Tuplet self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.actual, serializer);
    sse_encode_u_32(self.normal, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
