#!/usr/bin/env python3
"""Compiles the course corpus into the idempotent seed script.

Source of truth: backend/content/courses/*.json (one file per course, validated
by apps/music/test/courses/content_corpus_test.dart with the real client
parser). Output: backend/scripts/seed_courses.sql — run with:

    set -a; source backend/.env; set +a
    psql "$CYMBRA_MUSIC_DATABASE_URL" -f backend/scripts/seed_courses.sql

Deliberately stdlib-only. Payloads are dollar-quoted; the tag is asserted
absent from every payload so no content can escape its quoting.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "content" / "courses"
OUT = ROOT / "scripts" / "seed_courses.sql"
TAG = "$cymbra$"

HEADER = """\
-- GENERATED by backend/scripts/gen_seed_courses.py — DO NOT EDIT.
-- Source of truth: backend/content/courses/*.json (see its README.md).
-- Idempotent upsert; safe to re-run against the music DB.

INSERT INTO music.courses
  (id, status, instrument, track, level, unit, unit_title, sort_order,
   schema_version, title, content)
VALUES
"""

FOOTER = """\
ON CONFLICT (id) DO UPDATE SET
  status = EXCLUDED.status, instrument = EXCLUDED.instrument,
  track = EXCLUDED.track, level = EXCLUDED.level,
  unit = EXCLUDED.unit, unit_title = EXCLUDED.unit_title,
  sort_order = EXCLUDED.sort_order, schema_version = EXCLUDED.schema_version,
  title = EXCLUDED.title, content = EXCLUDED.content, updated_at = now();

-- Retire the pre-curriculum seed rows (superseded by the corpus: the target
-- was a solfège curriculum, not app tutorials). Progress rows are per-user
-- and unreferenced, so they age out harmlessly.
DELETE FROM music.courses WHERE id IN
  ('sol-reading-staff', 'sol-note-names', 'sol-note-values',
   'app-synthesia', 'app-partition');
"""


def quoted(payload: str) -> str:
    if TAG in payload:
        sys.exit(f"payload contains the dollar-quote tag {TAG!r}")
    return f"{TAG}{payload}{TAG}"


def lit(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main() -> None:
    files = sorted(CONTENT.glob("*.json"))
    if not files:
        sys.exit(f"no course files under {CONTENT}")

    rows = []
    for path in files:
        doc = json.loads(path.read_text(encoding="utf-8"))
        if doc["id"] != path.stem:
            sys.exit(f"{path.name}: id {doc['id']!r} does not match filename")
        compact = dict(separators=(",", ":"), ensure_ascii=False)
        rows.append(
            "(\n"
            f"  {lit(doc['id'])}, {lit(doc['status'])}, {lit(doc['instrument'])},"
            f" {lit(doc['track'])}, {lit(doc['level'])},\n"
            f"  {lit(doc['unit'])}, {quoted(json.dumps(doc['unitTitle'], **compact))},"
            f" {doc['sortOrder']}, {doc['schemaVersion']},\n"
            f"  {quoted(json.dumps(doc['title'], **compact))},\n"
            f"  {quoted(json.dumps(doc['content'], **compact))}\n"
            ")"
        )

    OUT.write_text(HEADER + ",\n".join(rows) + "\n" + FOOTER, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} with {len(rows)} courses")


if __name__ == "__main__":
    main()
