<script setup lang="ts">
import { computed, ref, toRef } from "vue";
import { useI18n } from "vue-i18n";
import { match } from "ts-pattern";
import type { CatalogHit } from "@/gen/score_pb";
import { type Async, idle } from "@/lib/async";
import type { RenderResult } from "@/lib/notation/painter";
import { startOfWrittenMeasure, type PlaybackSchedule } from "@/lib/notation/schedule";
import { usePlayhead } from "@/composables/usePlayhead";

// Isolated preview module (design D5). Presentational: it shows metadata, the notation
// the renderer seam produces (`notation`), and a Play/Pause transport whose audio +
// clock live in the player composable (passed in as `schedule`/`elapsedMs`/`playing`).
// It touches no engine or API — only displays state and emits `toggle`. The playhead
// overlay (cursor + note highlight) is driven by `usePlayhead`.
const props = defineProps<{
  hit: CatalogHit | null;
  bytes: Uint8Array | null;
  loading: boolean;
  bytesError?: string | null;
  notation?: Async<RenderResult>;
  schedule?: Async<PlaybackSchedule>;
  audio?: Async<void>;
  elapsedMs?: number;
  playing?: boolean;
  canPlay?: boolean;
  // Opt IN to the read-only metadata summary (the moderation screens show it; a bare
  // preview elsewhere doesn't). Absent boolean props are cast to `false` by Vue, so
  // "off" is the default.
  showMeta?: boolean;
  // Opt OUT of rendering the Play/Pause transport here — set in review mode, where the
  // transport is hoisted next to the accept/reject buttons (one action row). Phrased as
  // an opt-out because Vue casts an absent boolean prop to `false`, so the default has
  // to be the "transport visible" case.
  hideTransport?: boolean;
  // The Play guard is lifted (change: add-drum-audio-channel) — a percussion
  // score auditions on the drum channel with a kit font. What remains is the one
  // honest degradation: the catalog holds no accepted percussion-family font, so
  // Play shows a localised "no drum kit available" note — distinct from an
  // error, since the score is fine.
  noKitFont?: boolean;
}>();
const emit = defineEmits<{ toggle: []; seek: [ms: number] }>();
const { t } = useI18n();

// Fold the notation render state into what to show. The SVG is generated by our own
// painter from parsed geometry (no user markup), so v-html is safe; on any failure we
// degrade to a placeholder, never a raw error string.
// The placeholder shown before/while the notation isn't a rendered SVG.
function idleMessage(): string {
  if (props.loading) return t("preview.loading");
  if (props.bytesError) return props.bytesError;
  if (props.bytes) return t("preview.rendering");
  return t("preview.noBytes");
}

const notationView = computed(() =>
  match(props.notation ?? idle)
    .with({ status: "success", data: { kind: "notation" } }, ({ data }) => ({ kind: "svg" as const, svg: data.svg }))
    .with({ status: "loading" }, () => ({ kind: "msg" as const, msg: t("preview.rendering") }))
    .with({ status: "error" }, () => ({ kind: "msg" as const, msg: t("preview.renderError") }))
    .otherwise(() => ({ kind: "msg" as const, msg: idleMessage() })),
);

// A short note under the transport: loading the audio, or a non-fatal audio error.
const audioMsg = computed(() =>
  match(props.audio ?? idle)
    .with({ status: "loading" }, () => t("preview.audioLoading"))
    .with({ status: "error" }, () => t("preview.audioError"))
    .otherwise(() => null),
);
// Whether the first-play data fetch (the ~57 MB SoundFont) is in flight — drives a
// small spinner so the moderator sees something is loading during the download.
const audioLoading = computed(() => (props.audio ?? idle).status === "loading");

const wrapRef = ref<HTMLElement | null>(null);
const svgString = computed(() => (notationView.value.kind === "svg" ? notationView.value.svg : null));
const layout = computed(() =>
  props.notation?.status === "success" && props.notation.data.kind === "notation" ? props.notation.data.layout : null,
);
const scheduleData = computed(() => (props.schedule?.status === "success" ? props.schedule.data : null));
usePlayhead({
  container: wrapRef,
  svg: svgString,
  layout,
  schedule: scheduleData,
  elapsedMs: toRef(() => props.elapsedMs ?? 0),
  playing: toRef(() => props.playing ?? false),
  // Click a measure → play from its start time (resolved via the schedule).
  onSeekMeasure: (i) => {
    // Taps land on engraved (written) measures: seek to their first played slot.
    const ms = scheduleData.value ? startOfWrittenMeasure(scheduleData.value, i) : null;
    if (ms != null) emit("seek", ms);
  },
});

function meta(): { label: string; value: string }[] {
  const h = props.hit;
  if (!h) return [];
  return [
    { label: t("preview.title"), value: h.title || "—" },
    { label: t("preview.composer"), value: h.composer || "—" },
    { label: t("preview.arranger"), value: h.arranger || "—" },
    { label: t("preview.level"), value: h.level || "—" },
    { label: t("preview.licence"), value: h.license },
    { label: t("preview.source"), value: h.source },
    { label: t("preview.timeSig"), value: h.timeSig || "—" },
    { label: t("preview.notes"), value: h.noteCount != null ? String(h.noteCount) : "—" },
    { label: t("preview.tempo"), value: h.tempoBpm != null ? String(h.tempoBpm) : "—" },
  ];
}
</script>

<template>
  <div class="preview">
    <dl v-if="showMeta" class="meta">
      <template v-for="m in meta()" :key="m.label">
        <dt>{{ m.label }}</dt>
        <dd>{{ m.value }}</dd>
      </template>
    </dl>

    <div v-if="notationView.kind === 'svg'" class="score">
      <div v-if="!hideTransport" class="transport">
        <button type="button" class="play" :disabled="!canPlay" @click="emit('toggle')">
          {{ playing ? t("preview.pause") : t("preview.play") }}
        </button>
        <output v-if="audioLoading" class="spinner" :aria-label="audioMsg ?? ''"></output>
        <span v-if="audioMsg" class="muted">{{ audioMsg }}</span>
        <!-- No accepted kit font in the catalog: explains the disabled Play —
             deliberately NOT styled as an error; the notation above renders fine. -->
        <span v-else-if="noKitFont" class="muted" data-testid="no-drum-kit">{{ t("preview.noDrumKit") }}</span>
        <span v-else class="muted hint">{{ t("preview.seekHint") }}</span>
      </div>
      <!-- The transport moved out (review mode): keep the seek affordance visible —
           unless the missing kit font makes seeking inert (the host view shows its
           own "no drum kit available" note next to the hoisted transport). -->
      <p v-else-if="!noKitFont" class="muted hint transport-hint">{{ t("preview.seekHint") }}</p>
      <!-- eslint-disable-next-line vue/no-v-html -- SVG is painter-generated, not user input -->
      <div ref="wrapRef" class="svg-wrap" aria-label="score preview" v-html="notationView.svg"></div>
    </div>
    <div v-else class="notation" aria-label="score preview">
      <p class="muted">{{ notationView.msg }}</p>
    </div>
  </div>
</template>

<style scoped>
.preview {
  /* Stacked: file info on top, the notation below (full width). */
  display: flex;
  flex-direction: column;
  gap: 1rem;
}
.meta {
  display: grid;
  grid-template-columns: max-content 1fr;
  gap: 0.2rem 0.8rem;
  margin: 0;
  align-content: start;
}
.meta dt {
  color: var(--muted);
}
.meta dd {
  margin: 0;
}
.notation {
  min-height: 220px;
  border: 1px dashed var(--border);
  border-radius: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 1rem;
  text-align: center;
}
.score {
  display: flex;
  flex-direction: column;
  gap: 0.6rem;
}
.transport {
  display: flex;
  align-items: center;
  gap: 0.6rem;
}
.play {
  min-width: 5rem;
}
.hint {
  font-size: 0.85rem;
}
.transport-hint {
  margin: 0;
}
/* Small spinner shown while the first-play data (SoundFont) downloads. */
.spinner {
  width: 1rem;
  height: 1rem;
  border: 2px solid var(--border-2);
  border-top-color: var(--teal);
  border-radius: 50%;
  animation: spin 0.7s linear infinite;
}
@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
.svg-wrap {
  border: 1px solid var(--border);
  border-radius: 8px;
  padding: 1rem;
  /* The score can be tall/wide; scroll it inside the box and let the playhead
     auto-scroll to follow playback. */
  max-height: 60vh;
  overflow: auto;
}
.svg-wrap :deep(svg) {
  max-width: 100%;
  height: auto;
}
.muted {
  color: var(--muted);
}
</style>
