<script setup lang="ts">
import { computed } from "vue";
import { useI18n } from "vue-i18n";
import { match } from "ts-pattern";
import type { CatalogHit } from "@/gen/score_pb";
import { type Async, idle } from "@/lib/async";

// Isolated preview module (design D5). Presentational only: it shows metadata and
// the notation the renderer seam (useScoreRenderer → wasm `layout_systems` + the SVG
// SMuFL painter) produces, passed in as `notation`. The wasm call lives in the
// composable, not here — so this component never touches the engine and the renderer
// can be swapped for a JS fallback without touching the console.
const props = defineProps<{
  hit: CatalogHit | null;
  bytes: Uint8Array | null;
  loading: boolean;
  bytesError?: string | null;
  notation?: Async<string>;
}>();
const { t } = useI18n();

// Fold the notation render state into what to show in the .notation box. The SVG is
// generated by our own painter from parsed geometry (no user markup), so v-html is
// safe here; on any failure we degrade to a placeholder, never a raw error string.
const notationView = computed(() =>
  match(props.notation ?? idle)
    .with({ status: "success" }, ({ data }) => ({ kind: "svg" as const, svg: data }))
    .with({ status: "loading" }, () => ({ kind: "msg" as const, msg: t("preview.rendering") }))
    .with({ status: "error" }, () => ({ kind: "msg" as const, msg: t("preview.renderError") }))
    .otherwise(() =>
      props.loading
        ? { kind: "msg" as const, msg: t("preview.loading") }
        : props.bytesError
          ? { kind: "msg" as const, msg: props.bytesError }
          : props.bytes
            ? { kind: "msg" as const, msg: t("preview.rendering") }
            : { kind: "msg" as const, msg: t("preview.noBytes") },
    ),
);

function meta(): { label: string; value: string }[] {
  const h = props.hit;
  if (!h) return [];
  return [
    { label: t("preview.title"), value: h.title || "—" },
    { label: t("preview.composer"), value: h.composer || "—" },
    { label: t("preview.arranger"), value: h.arranger || "—" },
    { label: t("preview.level"), value: h.level || "—" },
    { label: t("preview.licence"), value: h.license },
    { label: t("preview.source"), value: h.source },
    { label: t("preview.timeSig"), value: h.timeSig || "—" },
    { label: t("preview.notes"), value: h.noteCount != null ? String(h.noteCount) : "—" },
    { label: t("preview.tempo"), value: h.tempoBpm != null ? String(h.tempoBpm) : "—" },
  ];
}
</script>

<template>
  <div class="preview">
    <dl class="meta">
      <template v-for="m in meta()" :key="m.label">
        <dt>{{ m.label }}</dt>
        <dd>{{ m.value }}</dd>
      </template>
    </dl>

    <div class="notation" aria-label="score preview">
      <!-- eslint-disable-next-line vue/no-v-html -- SVG is painter-generated, not user input -->
      <div v-if="notationView.kind === 'svg'" class="svg-wrap" v-html="notationView.svg"></div>
      <p v-else class="muted">{{ notationView.msg }}</p>
    </div>
  </div>
</template>

<style scoped>
.preview {
  display: grid;
  grid-template-columns: 220px 1fr;
  gap: 1rem;
}
.meta {
  display: grid;
  grid-template-columns: max-content 1fr;
  gap: 0.2rem 0.8rem;
  margin: 0;
  align-content: start;
}
.meta dt {
  color: var(--muted);
}
.meta dd {
  margin: 0;
}
.notation {
  min-height: 220px;
  border: 1px dashed var(--border);
  border-radius: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 1rem;
  text-align: center;
  /* The rendered score can be wide; scroll it inside the box rather than clip. */
  overflow-x: auto;
}
.svg-wrap {
  width: 100%;
  display: flex;
  justify-content: center;
}
.svg-wrap :deep(svg) {
  max-width: 100%;
  height: auto;
}
.muted {
  color: var(--muted);
}
</style>
