// The single seam to the WebAssembly notation renderer. Lazy — the wasm module (and
// its ~300KB binary) is only fetched/instantiated on first use, and only once. Kept
// behind this function so the renderer can be swapped for a pure-JS fallback, and so
// unit tests inject a stub via `setNotationWasmForTest` without instantiating wasm
// (jsdom can't run the module), mirroring the gRPC `api()` seam.

import type { RenderedScore } from "./geometry";

export interface NotationWasm {
  /** Parse score bytes and lay them out at `width`; throws on non-MusicXML input. */
  render(bytes: Uint8Array, width: number): RenderedScore;
}

let cached: Promise<NotationWasm> | null = null;

/** Load (once) and return the wasm renderer. Subsequent calls reuse the instance. */
export function loadNotationWasm(): Promise<NotationWasm> {
  if (cached) return cached;
  cached = (async () => {
    // Generated by `yarn gen:wasm` (gitignored). The default export instantiates the
    // module (fetching the sibling _bg.wasm via import.meta.url); `render` is the
    // wrapper crate's entry point.
    const mod = await import("@/wasm/pkg/musicxml_wasm.js");
    await mod.default();
    return {
      render: (bytes: Uint8Array, width: number) => mod.render(bytes, width) as RenderedScore,
    };
  })();
  return cached;
}

/** Test seam: inject a stub renderer (or reset with `null`). */
export function setNotationWasmForTest(w: NotationWasm | null): void {
  cached = w ? Promise.resolve(w) : null;
}
