// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply`, `clamp7`, `new`, `note_off`, `note_on`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AudioEvent`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`

/// Tracks which pitches are currently sounding so the audio thread can release
/// them precisely on an [`AudioEvent::AllOff`] and so the model is testable
/// without a synthesizer.
///
/// rustysynth manages its own voices internally; this mirror lets `audio.rs`
/// issue an exact note-off per held pitch (and lets tests assert the bookkeeping
/// without a device).
class VoiceTracker {
  final Uint8List active;

  const VoiceTracker({required this.active});

  static Future<VoiceTracker> default_() =>
      RustLib.instance.api.crateApiAudioCoreVoiceTrackerDefault();

  @override
  int get hashCode => active.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VoiceTracker &&
          runtimeType == other.runtimeType &&
          active == other.active;
}
