// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_stream`, `run_audio_thread`, `send`

/// Initializes the synthesizer from a SoundFont (`.sf2`) file path and starts
/// the audio output. Idempotent: a second call keeps the first engine.
///
/// Returns immediately — the heavy work (reading + parsing the ~50 MB SoundFont
/// and opening the device) runs on the dedicated audio thread, reading straight
/// from disk so the UI isolate never blocks and no large buffer crosses the
/// bridge. If the font is missing/invalid or no device can be opened the engine
/// stays silent (note events become no-ops); the app keeps working.
void audioInit({required String sf2Path}) =>
    RustLib.instance.api.crateApiAudioAudioInit(sf2Path: sf2Path);

/// Sounds a piano voice for `pitch` at `velocity` (both 7-bit MIDI; 0 velocity
/// is treated as a default mezzo-forte for sources without pressure).
void noteOn({required int pitch, required int velocity}) =>
    RustLib.instance.api.crateApiAudioNoteOn(pitch: pitch, velocity: velocity);

/// Releases the voice for `pitch` (it enters the SoundFont's release stage).
void noteOff({required int pitch}) =>
    RustLib.instance.api.crateApiAudioNoteOff(pitch: pitch);

/// Releases every sounding voice (stop / restart / seek / loop).
void allNotesOff() => RustLib.instance.api.crateApiAudioAllNotesOff();

/// Sounds a short metronome click — a synthesized tick mixed into the output
/// independently of the piano SoundFont. `accent` marks the downbeat (higher and
/// louder). Self-terminating: there is no matching off.
void metronomeClick({required bool accent}) =>
    RustLib.instance.api.crateApiAudioMetronomeClick(accent: accent);
