// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_stream`, `run_audio_thread`, `send`

/// Initializes the synthesizer from SoundFont (`.sf2`) bytes and starts the
/// audio output. Idempotent: a second call keeps the first engine.
///
/// Returns immediately — the heavy work (parsing the ~50 MB SoundFont and
/// opening the device) runs on the dedicated audio thread so the UI isolate
/// never blocks. If the font is invalid or no device can be opened the engine
/// stays silent (note events become no-ops); the app keeps working.
///
/// NOT `#[frb(sync)]`: the SoundFont bytes are marshalled and handled off the
/// UI thread, so even moving the buffer across the bridge can't jank the UI.
Future<void> audioInit({required List<int> sf2Bytes}) =>
    RustLib.instance.api.crateApiAudioAudioInit(sf2Bytes: sf2Bytes);

/// Sounds a piano voice for `pitch` at `velocity` (both 7-bit MIDI; 0 velocity
/// is treated as a default mezzo-forte for sources without pressure).
void noteOn({required int pitch, required int velocity}) =>
    RustLib.instance.api.crateApiAudioNoteOn(pitch: pitch, velocity: velocity);

/// Releases the voice for `pitch` (it enters the SoundFont's release stage).
void noteOff({required int pitch}) =>
    RustLib.instance.api.crateApiAudioNoteOff(pitch: pitch);

/// Releases every sounding voice (stop / restart / seek / loop).
void allNotesOff() => RustLib.instance.api.crateApiAudioAllNotesOff();
