// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_capture`, `capture_thread`, `install_detector`, `to_midi_event`, `wait_until`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Starts microphone capture, returning whether capture is running afterwards.
/// Idempotent: calling while already capturing changes nothing. Failure to
/// open a device (no input hardware, permission denied at the OS layer) leaves
/// the lifecycle idle and returns `false` — graceful degradation, no panic.
bool audioInputStartCapture() =>
    RustLib.instance.api.crateApiAudioInputAudioInputStartCapture();

/// Stops microphone capture and releases the device. Idempotent.
void audioInputStopCapture() =>
    RustLib.instance.api.crateApiAudioInputAudioInputStopCapture();

/// Whether microphone capture is currently running.
bool audioInputIsCapturing() =>
    RustLib.instance.api.crateApiAudioInputAudioInputIsCapturing();

/// Names of the available capture devices, default first. Desktop hosts
/// expose no transport type, so every kind is [`InputRouteKind::Other`];
/// mobile route kinds come from the platform session via
/// [`classify_input_route_token`].
List<AudioInputInfo> listAudioInputs() =>
    RustLib.instance.api.crateApiAudioInputListAudioInputs();

/// Classifies a platform port-type identifier (iOS `AVAudioSession.Port` raw
/// value, Android `AudioDeviceInfo` type name) into a route kind. Unknown
/// tokens degrade to [`InputRouteKind::Other`].
InputRouteKind classifyInputRouteToken({required String token}) => RustLib
    .instance
    .api
    .crateApiAudioInputClassifyInputRouteToken(token: token);

/// The acquisition verdict for a route kind.
InputRouteVerdict inputRouteVerdictFor({required InputRouteKind kind}) =>
    RustLib.instance.api.crateApiAudioInputInputRouteVerdictFor(kind: kind);

/// Starts acoustic note detection (spec: Detected Notes Enter The Standard
/// Input Stream): ensures capture runs and installs the detector as soon as
/// the device rate is known. Returns whether capture is running. Detection
/// emits nothing until [`set_expected_pitches`] provides a non-empty window.
bool audioInputStartDetection() =>
    RustLib.instance.api.crateApiAudioInputAudioInputStartDetection();

/// Stops acoustic note detection. Capture is left to its own lifecycle — the
/// app owns when the microphone closes (spec: Microphone Capture Lifecycle).
void audioInputStopDetection() =>
    RustLib.instance.api.crateApiAudioInputAudioInputStopDetection();

/// Replaces the expected-pitch window the presence stage evaluates (spec:
/// Score-Informed Presence Detection). The app pushes it on every playhead /
/// Wait-gate change; an empty list idles the detector.
void setExpectedPitches({required List<int> pitches}) =>
    RustLib.instance.api.crateApiAudioInputSetExpectedPitches(pitches: pitches);

/// Chooses the capture device (`None` = follow the system default) and
/// applies it to a capture already running by rebuilding the stream (spec:
/// Desktop Capture Device Selection). An absent name degrades to the default
/// at open time rather than failing.
void setAudioInput({String? name}) =>
    RustLib.instance.api.crateApiAudioInputSetAudioInput(name: name);

/// The device the running capture is actually acquiring from, or `None` when
/// idle. Reality, not the request: a fallback shows the default's name.
String? activeAudioInput() =>
    RustLib.instance.api.crateApiAudioInputActiveAudioInput();

/// The device a capture is acquiring from right now — or, when idle, the one
/// a capture WOULD open (the pinned selection resolved against what is
/// present, falling back to the system default). The calibration store keys
/// measurements by this name, so it must always describe the device that
/// actually answers.
String? resolvedAudioInput() =>
    RustLib.instance.api.crateApiAudioInputResolvedAudioInput();

/// Runs one input-offset calibration: captures, observes the noise floor,
/// emits the reference click through the existing output path, and measures
/// when it arrives back at the microphone. Blocking — the bridge runs it off
/// the UI thread and hands Dart a future. Capture started here is stopped
/// here; capture already running stays running.
Future<InputCalibrationResult> runInputCalibration() =>
    RustLib.instance.api.crateApiAudioInputRunInputCalibration();

/// An audio input the engine can capture from.
class AudioInputInfo {
  /// The host's name for the device — display + persistence handle.
  final String name;

  /// How it is connected (desktop enumeration: always [`InputRouteKind::Other`]).
  final InputRouteKind kind;

  const AudioInputInfo({required this.name, required this.kind});

  @override
  int get hashCode => name.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioInputInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          kind == other.kind;
}

/// The terminal result of one calibration run (spec: Measured Input-Offset
/// Calibration). `detected == false` means the click was never heard — the
/// app shows guidance and stores nothing.
class InputCalibrationResult {
  /// Whether the reference click was detected at the microphone.
  final bool detected;

  /// The measured emission→capture round trip, when detected.
  final double? latencyMs;

  const InputCalibrationResult({required this.detected, this.latencyMs});

  @override
  int get hashCode => detected.hashCode ^ latencyMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InputCalibrationResult &&
          runtimeType == other.runtimeType &&
          detected == other.detected &&
          latencyMs == other.latencyMs;
}

/// How a capture route is connected, as the app reasons about it. The input
/// twin of the output side's `AudioRouteKind` — classified from the
/// platform's stable port-type identifier, never from a display name.
enum InputRouteKind {
  /// The device's own microphone.
  builtin,

  /// A wired headset microphone or line input.
  wired,

  /// A USB audio device — including a wireless mic's USB-C receiver, which
  /// enumerates as class-compliant USB audio and is wired-equivalent.
  usb,

  /// A Bluetooth microphone (the HFP/SCO voice profile).
  bluetooth,

  /// Anything the platform does not describe well enough to classify —
  /// including every desktop device, where cpal exposes no transport type.
  other,
}

/// The acquisition verdict for a route: Bluetooth capture is refused outright
/// (spec: Bluetooth Input Refusal), everything else is accepted.
enum InputRouteVerdict {
  /// The route may acquire.
  accepted,

  /// A Bluetooth microphone: voice-profile bandwidth and jitter are
  /// incompatible with note timing. Hard refusal, with copy in the app.
  refusedBluetooth,
}
