// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `current_port_names`, `midi_echo`, `open_connections`, `try_connect`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`

/// Chooses what the engine sounds for live MIDI events from now on, and returns
/// immediately (see [`MidiEcho`]). Pushed by the app whenever its own answer
/// changes — the loaded score's family, the kit font becoming ready, the
/// instrument-sounds-itself setting, leaving the player — and `Off` is always a
/// safe value: it simply leaves the sounding to the app.
void setMidiEcho({required MidiEcho mode}) =>
    RustLib.instance.api.crateApiMidiSetMidiEcho(mode: mode);

/// Replaces the input mapping the engine applies to its own echo, and returns
/// immediately. An empty list clears it.
///
/// The same shape as [`set_midi_echo`]: the **app owns the policy** — which
/// device is connected, what it was calibrated to — and pushes it on every
/// input that can change the answer. Idempotent, so over-calling is safe.
///
/// The engine applies this to what it *sounds*, never to what it *reports*: the
/// raw number still reaches the bridge, because the input monitor exists to
/// show a player what their instrument actually sends.
void setMidiMapping({required List<MidiMappingEntry> entries}) =>
    RustLib.instance.api.crateApiMidiSetMidiMapping(entries: entries);

/// Lists the names of available MIDI input ports (UI selection).
/// Virtual ports ("Midi Through", rtpmidi…) are placed last.
List<String> listMidiPorts() =>
    RustLib.instance.api.crateApiMidiListMidiPorts();

/// Name of the currently connected MIDI port, or `None` if no device.
/// Polled periodically by Flutter for the connection indicator.
String? connectedPort() => RustLib.instance.api.crateApiMidiConnectedPort();

/// Chooses the MIDI device to listen to (by name). `None` = auto mode
/// (first non-virtual port). Forces an immediate reconnection to the new port.
void setMidiPort({String? name}) =>
    RustLib.instance.api.crateApiMidiSetMidiPort(name: name);

/// Starts MIDI watching and streams NoteOn/NoteOff into `sink`.
///
/// The thread connects to the first available port, reconnects on hot-plug,
/// and releases the connection on unplug.
Stream<MidiEvent> midiEventStream() =>
    RustLib.instance.api.crateApiMidiMidiEventStream();

/// What the **engine itself** sounds for a live MIDI event, straight from the
/// MIDI callback (change: add-drum-input-mapping — beta fix "strong latency
/// between the hit and the sound").
///
/// A live note used to be sounded by Dart: the engine forwarded the event over
/// the bridge, the notifier handled it, and only then called back into the
/// engine to play it. Everything in that round trip rides the UI isolate's
/// event loop, so the delay a player hears is whatever the app happens to be
/// doing that frame — on a kit, where the stick has already left the head, that
/// is the difference between an instrument and a lag.
///
/// The app stays in charge of the *policy* — whether to sound at all
/// (instrument-sounds-itself), and on which channel — by pushing the mode here
/// ([`set_midi_echo`]); the engine only executes it, and the app then leaves
/// the sounding of MIDI notes alone so nothing is played twice.
enum MidiEcho {
  /// The engine sounds nothing: the app plays live notes itself, or the
  /// instrument already sounds them.
  off,

  /// Sound on the melodic channel, with the matching release — a keyboard.
  melodic,

  /// Sound on the drum channel as a one-shot, releases dropped, exactly as a
  /// percussion stroke is played (a kit's note-off arrives milliseconds after
  /// its attack and would cut the voice).
  drum,
}

/// A normalized MIDI event, ready to be consumed by Flutter.
class MidiEvent {
  final MidiEventKind kind;

  /// MIDI note number (0-127).
  final int pitch;

  /// Velocity (0-127). 0 for a NoteOff.
  final int velocity;

  /// Transmitting MIDI channel, 0-based (channel 10 — General MIDI
  /// percussion — is `9`). Reported so a diagnostic surface can show a player
  /// what their instrument sends; **never** used to accept or reject an
  /// event, which stays channel-agnostic (change: add-drum-input-calibration).
  final int channel;

  /// Timestamp since the stream was opened, in milliseconds.
  final BigInt timestampMs;

  const MidiEvent({
    required this.kind,
    required this.pitch,
    required this.velocity,
    required this.channel,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      pitch.hashCode ^
      velocity.hashCode ^
      channel.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MidiEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          pitch == other.pitch &&
          velocity == other.velocity &&
          channel == other.channel &&
          timestampMs == other.timestampMs;
}

/// MIDI event type forwarded to Flutter.
///
/// `Copy` so the input callback can name the kind of the event it is echoing
/// without consuming the one it still has to report (change:
/// add-drum-input-calibration) — a fieldless enum, so it costs nothing.
enum MidiEventKind { noteOn, noteOff }

/// One learned translation: the number the instrument sends, and what it means.
class MidiMappingEntry {
  /// The number as the instrument transmits it.
  final int from;

  /// The General MIDI number the app reasons in.
  final int to;

  const MidiMappingEntry({required this.from, required this.to});

  @override
  int get hashCode => from.hashCode ^ to.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MidiMappingEntry &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to;
}
