// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `current_port_names`, `try_connect`

/// Lists the names of available MIDI input ports (UI selection).
/// Virtual ports ("Midi Through", rtpmidi…) are placed last.
List<String> listMidiPorts() =>
    RustLib.instance.api.crateApiMidiListMidiPorts();

/// Name of the currently connected MIDI port, or `None` if no device.
/// Polled periodically by Flutter for the connection indicator.
String? connectedPort() => RustLib.instance.api.crateApiMidiConnectedPort();

/// Chooses the MIDI device to listen to (by name). `None` = auto mode
/// (first non-virtual port). Forces an immediate reconnection to the new port.
void setMidiPort({String? name}) =>
    RustLib.instance.api.crateApiMidiSetMidiPort(name: name);

/// Starts MIDI watching and streams NoteOn/NoteOff into `sink`.
///
/// The thread connects to the first available port, reconnects on hot-plug,
/// and releases the connection on unplug.
Stream<MidiEvent> midiEventStream() =>
    RustLib.instance.api.crateApiMidiMidiEventStream();

/// A normalized MIDI event, ready to be consumed by Flutter.
class MidiEvent {
  final MidiEventKind kind;

  /// MIDI note number (0-127).
  final int pitch;

  /// Velocity (0-127). 0 for a NoteOff.
  final int velocity;

  /// Timestamp since the stream was opened, in milliseconds.
  final BigInt timestampMs;

  const MidiEvent({
    required this.kind,
    required this.pitch,
    required this.velocity,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ pitch.hashCode ^ velocity.hashCode ^ timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MidiEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          pitch == other.pitch &&
          velocity == other.velocity &&
          timestampMs == other.timestampMs;
}

/// MIDI event type forwarded to Flutter.
enum MidiEventKind { noteOn, noteOff }
