// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'musicxml.freezed.dart';

/// Parses a MusicXML document (bytes) into a [`ScoreDocument`], with each
/// measure's `min_width` already computed. A zipped `.mxl` container is decoded
/// first (same sniff as [`validate_musicxml`]), so the caller can pass the raw
/// picked file — plain `.musicxml`/`.xml` or `.mxl`. Errors on malformed input
/// rather than panicking.
Future<ScoreDocument> parseMusicxml({required List<int> bytes}) =>
    RustLib.instance.api.crateApiMusicxmlParseMusicxml(bytes: bytes);

/// Validates raw bytes (plain MusicXML or a zipped `.mxl`) client-side, using the
/// **same** shared gate as the backend upload path — so a file that previews here
/// is accepted server-side (and vice-versa). Never panics.
Future<ValidationOutcome> validateMusicxml({required List<int> bytes}) =>
    RustLib.instance.api.crateApiMusicxmlValidateMusicxml(bytes: bytes);

/// Lays the document's measures out into [`System`]s for the given available
/// width (pixels), keeping measure order and the grand staff together.
List<System> layoutSystems({
  required ScoreDocument doc,
  required double availableWidth,
}) => RustLib.instance.api.crateApiMusicxmlLayoutSystems(
  doc: doc,
  availableWidth: availableWidth,
);

/// Starting musical attributes of the part (most-recent values win).
class Attributes {
  /// Divisions (ticks) per quarter note — the unit for every `duration`.
  final int divisions;

  /// One clef per staff, identified by clef `number`.
  final List<Clef> clefs;

  /// Key signature, in fifths on the circle (negative = flats).
  final int keyFifths;
  final TimeSignature time;

  const Attributes({
    required this.divisions,
    required this.clefs,
    required this.keyFifths,
    required this.time,
  });

  @override
  int get hashCode =>
      divisions.hashCode ^ clefs.hashCode ^ keyFifths.hashCode ^ time.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Attributes &&
          runtimeType == other.runtimeType &&
          divisions == other.divisions &&
          clefs == other.clefs &&
          keyFifths == other.keyFifths &&
          time == other.time;
}

/// Beam state at a note within a beam group.
enum BeamState { begin, continue_, end }

/// A clef on one staff: e.g. treble = `G`/2 on staff 1, bass = `F`/4 on staff 2.
class Clef {
  final int staff;
  final ClefSign sign;
  final int line;

  const Clef({required this.staff, required this.sign, required this.line});

  @override
  int get hashCode => staff.hashCode ^ sign.hashCode ^ line.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Clef &&
          runtimeType == other.runtimeType &&
          staff == other.staff &&
          sign == other.sign &&
          line == other.line;
}

/// A clef sign the renderers act on. MusicXML defines seven signs; `TAB`,
/// `jianpu` and `none` are out of scope for a keyboard-and-drums product, and
/// an unrecognised sign leaves the staff at its default clef rather than
/// failing the parse.
enum ClefSign { g, f, c, percussion }

/// A measure direction (expression/tempo) anchored at a staff and time position.
class Direction {
  final int staff;
  final int positionDivisions;
  final DirectionKind kind;

  const Direction({
    required this.staff,
    required this.positionDivisions,
    required this.kind,
  });

  @override
  int get hashCode =>
      staff.hashCode ^ positionDivisions.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Direction &&
          runtimeType == other.runtimeType &&
          staff == other.staff &&
          positionDivisions == other.positionDivisions &&
          kind == other.kind;
}

@freezed
sealed class DirectionKind with _$DirectionKind {
  const DirectionKind._();

  /// Free expression/tempo text (e.g. "Andantino", "dolce").
  const factory DirectionKind.words(String field0) = DirectionKind_Words;

  /// A dynamics marking (e.g. "pp", "f").
  const factory DirectionKind.dynamics(String field0) = DirectionKind_Dynamics;

  /// A hairpin: `crescendo` true = opening (<), false = diminuendo (>).
  /// `stop` marks the end of a previously opened hairpin.
  const factory DirectionKind.wedge({
    required bool crescendo,
    required bool stop,
  }) = DirectionKind_Wedge;

  /// A metronome mark, e.g. quarter = 120.
  const factory DirectionKind.metronome({
    required String beatUnit,
    required int perMinute,
  }) = DirectionKind_Metronome;
}

/// How an unpitched note's head is engraved (change: add-drum-notation-render).
enum HeadClass {
  /// Ordinary oval head — drums, and any unresolved note.
  oval,

  /// X-form head — cymbals, following the duration class.
  x,

  /// X head carrying the open mark — the open hi-hat (GM 46).
  xOpen,
}

/// One `<score-instrument>` declaration from the part list.
class InstrumentDecl {
  /// The declaration's `id`, referenced by a note's `<instrument id>`.
  final String id;

  /// `<instrument-name>` when declared (e.g. "Snare Drum").
  final String? name;

  /// General MIDI percussion number (0-based) from `<midi-unpitched>`,
  /// already converted from the element's 1-based value.
  final int? gmNumber;

  const InstrumentDecl({required this.id, this.name, this.gmNumber});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ gmNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InstrumentDecl &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          gmNumber == other.gmNumber;
}

/// Which instrument family a score is written for, derived from its notation
/// alone — never from a filename, a part name, or any other external claim.
enum InstrumentKind {
  /// Every non-rest note is pitched.
  keyboard,

  /// Every non-rest note is unpitched.
  percussion,

  /// Mixed pitched and unpitched content, or no notes at all.
  unknown,
}

/// A lyric syllable attached to a note.
class Lyric {
  final String? syllabic;
  final String text;

  const Lyric({this.syllabic, required this.text});

  @override
  int get hashCode => syllabic.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Lyric &&
          runtimeType == other.runtimeType &&
          syllabic == other.syllabic &&
          text == other.text;
}

/// A measure: its notes and directions in document order, plus the engraving
/// minimum width computed from note density.
class NotationMeasure {
  /// 0-based position in the part.
  final int index;
  final List<NoteEvent> notes;
  final List<Direction> directions;

  /// Clef changes declared in this measure (empty when unchanged), so the
  /// renderer can switch clefs mid-piece (e.g. a left hand that starts in
  /// treble and moves to bass).
  final List<Clef> clefs;

  /// Key signature (fifths on the circle, negative = flats) in force during
  /// this measure, carried forward from the last `<key>` change. Lets the
  /// renderer draw the correct armure per system — and a key change where it
  /// differs from the previous measure — for a piece that modulates.
  final int keyFifths;

  /// Minimum engraving width (pixels) from the non-linear spacing function.
  final double minWidth;

  /// Repeat notation engraved on this measure (barline repeats, voltas,
  /// measure-repeat `%`, segno/coda and jump semantics). All defaults when
  /// the measure carries none — the overwhelmingly common case.
  final RepeatMarks repeats;

  const NotationMeasure({
    required this.index,
    required this.notes,
    required this.directions,
    required this.clefs,
    required this.keyFifths,
    required this.minWidth,
    required this.repeats,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      notes.hashCode ^
      directions.hashCode ^
      clefs.hashCode ^
      keyFifths.hashCode ^
      minWidth.hashCode ^
      repeats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotationMeasure &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          notes == other.notes &&
          directions == other.directions &&
          clefs == other.clefs &&
          keyFifths == other.keyFifths &&
          minWidth == other.minWidth &&
          repeats == other.repeats;
}

/// A single note (or rest) event.
class NoteEvent {
  final int staff;
  final int voice;

  /// Running time position within the measure (set via backup/forward), so
  /// notes on different staves/voices at the same beat share a column.
  final int positionDivisions;

  /// Pitch, or `None` for a rest.
  final Pitch? pitch;
  final bool isRest;

  /// True when this note carries `<chord/>` (sounds with the preceding note).
  final bool isChord;

  /// True when this note carries `<grace/>` — an ornamental small note that
  /// occupies no musical time (`duration_divisions` stays 0 and the cursor
  /// does not advance); playback gives it a short nominal duration stolen
  /// from just before its position.
  final bool isGrace;
  final int durationDivisions;

  /// Note-type token when present (e.g. "quarter", "eighth").
  final String? noteType;
  final int dots;

  /// Accidental token when present (e.g. "flat", "sharp", "natural").
  final String? accidental;
  final bool tieStart;
  final bool tieStop;

  /// Phrasing slur start/stop (legato arc spanning several notes).
  final bool slurStart;
  final bool slurStop;
  final Tuplet? tuplet;
  final StemDir? stem;
  final List<BeamState> beams;
  final Lyric? lyric;

  /// Written staff position of a percussion note (`<unpitched>`), with its
  /// resolved General MIDI number — a channel **distinct** from `pitch`: the
  /// written position is a staff placement, not a sounding pitch. A note is
  /// exactly one of pitched, unpitched, or a rest.
  final Unpitched? unpitched;

  /// The note's `<instrument id>` reference when present.
  final String? instrumentId;

  const NoteEvent({
    required this.staff,
    required this.voice,
    required this.positionDivisions,
    this.pitch,
    required this.isRest,
    required this.isChord,
    required this.isGrace,
    required this.durationDivisions,
    this.noteType,
    required this.dots,
    this.accidental,
    required this.tieStart,
    required this.tieStop,
    required this.slurStart,
    required this.slurStop,
    this.tuplet,
    this.stem,
    required this.beams,
    this.lyric,
    this.unpitched,
    this.instrumentId,
  });

  @override
  int get hashCode =>
      staff.hashCode ^
      voice.hashCode ^
      positionDivisions.hashCode ^
      pitch.hashCode ^
      isRest.hashCode ^
      isChord.hashCode ^
      isGrace.hashCode ^
      durationDivisions.hashCode ^
      noteType.hashCode ^
      dots.hashCode ^
      accidental.hashCode ^
      tieStart.hashCode ^
      tieStop.hashCode ^
      slurStart.hashCode ^
      slurStop.hashCode ^
      tuplet.hashCode ^
      stem.hashCode ^
      beams.hashCode ^
      lyric.hashCode ^
      unpitched.hashCode ^
      instrumentId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteEvent &&
          runtimeType == other.runtimeType &&
          staff == other.staff &&
          voice == other.voice &&
          positionDivisions == other.positionDivisions &&
          pitch == other.pitch &&
          isRest == other.isRest &&
          isChord == other.isChord &&
          isGrace == other.isGrace &&
          durationDivisions == other.durationDivisions &&
          noteType == other.noteType &&
          dots == other.dots &&
          accidental == other.accidental &&
          tieStart == other.tieStart &&
          tieStop == other.tieStop &&
          slurStart == other.slurStart &&
          slurStop == other.slurStop &&
          tuplet == other.tuplet &&
          stem == other.stem &&
          beams == other.beams &&
          lyric == other.lyric &&
          unpitched == other.unpitched &&
          instrumentId == other.instrumentId;
}

/// A pitch: diatonic step, octave, and chromatic alteration (semitones).
class Pitch {
  final String step;
  final int octave;
  final int alter;

  const Pitch({required this.step, required this.octave, required this.alter});

  @override
  int get hashCode => step.hashCode ^ octave.hashCode ^ alter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Pitch &&
          runtimeType == other.runtimeType &&
          step == other.step &&
          octave == other.octave &&
          alter == other.alter;
}

/// One slot of the playback order: which written measure plays, and which pass
/// through it this is (1-based — a repeated measure has one slot per pass).
class PlayedMeasure {
  final int writtenIndex;
  final int pass;

  const PlayedMeasure({required this.writtenIndex, required this.pass});

  @override
  int get hashCode => writtenIndex.hashCode ^ pass.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayedMeasure &&
          runtimeType == other.runtimeType &&
          writtenIndex == other.writtenIndex &&
          pass == other.pass;
}

/// The repeat structure engraved on one measure, in written order — everything
/// the unroll and the renderers need. Defaults mean "no repeat notation".
class RepeatMarks {
  /// A forward repeat (`‖:`) opens this measure.
  final bool forward;

  /// A backward repeat (`:‖`) closes this measure: the `times` attribute
  /// (how many times the section is played in total; MusicXML default 2).
  /// 0 = no backward repeat.
  final int backwardTimes;

  /// Volta numbers of an ending bracket **starting** at this measure
  /// (e.g. `[1]`, `[1, 2]`). Empty when none starts here.
  final Uint32List endingStart;

  /// An ending bracket **stops** (downward hook) at this measure.
  final bool endingStop;

  /// An ending bracket ends open (discontinue) at this measure — the usual
  /// engraving of a final volta.
  final bool endingDiscontinue;

  /// This is a measure-repeat (`%`) measure: the written measure whose
  /// content it replays (already resolved transitively for chained `%`
  /// runs). The measure's own note list stays empty — the sign is engraved,
  /// the referenced content is played.
  final int? measureRepeatOf;

  /// Slash count of the measure-repeat sign (1 = `%`).
  final int measureRepeatSlashes;

  /// A segno sign is placed at this measure.
  final bool segno;

  /// A coda sign is placed at this measure.
  final bool coda;

  /// `<sound>` jump semantics attached to this measure's directions.
  final bool soundDacapo;
  final bool soundDalsegno;
  final bool soundTocoda;
  final bool soundFine;

  /// `<sound forward-repeat="yes">` — repeats are re-taken after the jump.
  final bool soundForwardRepeat;

  const RepeatMarks({
    required this.forward,
    required this.backwardTimes,
    required this.endingStart,
    required this.endingStop,
    required this.endingDiscontinue,
    this.measureRepeatOf,
    required this.measureRepeatSlashes,
    required this.segno,
    required this.coda,
    required this.soundDacapo,
    required this.soundDalsegno,
    required this.soundTocoda,
    required this.soundFine,
    required this.soundForwardRepeat,
  });

  @override
  int get hashCode =>
      forward.hashCode ^
      backwardTimes.hashCode ^
      endingStart.hashCode ^
      endingStop.hashCode ^
      endingDiscontinue.hashCode ^
      measureRepeatOf.hashCode ^
      measureRepeatSlashes.hashCode ^
      segno.hashCode ^
      coda.hashCode ^
      soundDacapo.hashCode ^
      soundDalsegno.hashCode ^
      soundTocoda.hashCode ^
      soundFine.hashCode ^
      soundForwardRepeat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RepeatMarks &&
          runtimeType == other.runtimeType &&
          forward == other.forward &&
          backwardTimes == other.backwardTimes &&
          endingStart == other.endingStart &&
          endingStop == other.endingStop &&
          endingDiscontinue == other.endingDiscontinue &&
          measureRepeatOf == other.measureRepeatOf &&
          measureRepeatSlashes == other.measureRepeatSlashes &&
          segno == other.segno &&
          coda == other.coda &&
          soundDacapo == other.soundDacapo &&
          soundDalsegno == other.soundDalsegno &&
          soundTocoda == other.soundTocoda &&
          soundFine == other.soundFine &&
          soundForwardRepeat == other.soundForwardRepeat;
}

/// A parsed MusicXML document: metadata, staff count, starting attributes, and
/// the ordered measures with their notes, directions, and computed geometry.
class ScoreDocument {
  final ScoreMeta meta;

  /// Number of staves in the (single) part — e.g. 2 for a piano grand staff.
  final int staves;
  final Attributes attributes;

  /// The part-list instrument table: one entry per declared
  /// `<score-instrument>`, carrying the General MIDI percussion number its
  /// `<midi-instrument>/<midi-unpitched>` denotes. Empty for a score
  /// declaring no instruments (the overwhelmingly common keyboard case).
  final List<InstrumentDecl> instruments;
  final List<NotationMeasure> measures;

  /// The **playback order**: the sequence of written-measure passes a
  /// performer would play, resolved from the repeat structure (repeat
  /// barlines, voltas, D.C./D.S. jumps) with safety caps — the written order
  /// one-to-one when the piece has no repeats or the structure is malformed.
  /// Computed once at parse time; every derivation (app timeline, browser
  /// preview, server audio render) consumes it instead of re-resolving.
  final List<PlayedMeasure> playOrder;

  const ScoreDocument({
    required this.meta,
    required this.staves,
    required this.attributes,
    required this.instruments,
    required this.measures,
    required this.playOrder,
  });

  @override
  int get hashCode =>
      meta.hashCode ^
      staves.hashCode ^
      attributes.hashCode ^
      instruments.hashCode ^
      measures.hashCode ^
      playOrder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScoreDocument &&
          runtimeType == other.runtimeType &&
          meta == other.meta &&
          staves == other.staves &&
          attributes == other.attributes &&
          instruments == other.instruments &&
          measures == other.measures &&
          playOrder == other.playOrder;
}

/// Score metadata; fields are absent (`None`) rather than failing when missing.
class ScoreMeta {
  final String? title;
  final String? composer;

  const ScoreMeta({this.title, this.composer});

  @override
  int get hashCode => title.hashCode ^ composer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScoreMeta &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          composer == other.composer;
}

/// A parsed score's derived summary — the fields worth surfacing to a caller
/// (the contribution preview header) without re-parsing. Server-derived on
/// upload; this mirror lets the app show the same values it will store.
class ScoreSummary {
  final String? title;
  final String? composer;

  /// Accent-/case-folded title for typo-tolerant search.
  final String? titleNorm;

  /// Normalised `composer::title` key for dedup / grouping.
  final String workKey;

  /// Number of staves (2 for a piano grand staff).
  final int staves;
  final int keyFifths;

  /// `beats/beat_type`, e.g. `4/4`.
  final String timeSig;
  final int measureCount;

  /// Count of playable (pitched or unpitched, non-rest) note events — the
  /// validation gate's check; a percussion score reports a non-zero count.
  final int noteCount;

  /// Which instrument family the score is written for, derived from the
  /// notation alone.
  final InstrumentKind instrument;

  const ScoreSummary({
    this.title,
    this.composer,
    this.titleNorm,
    required this.workKey,
    required this.staves,
    required this.keyFifths,
    required this.timeSig,
    required this.measureCount,
    required this.noteCount,
    required this.instrument,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      composer.hashCode ^
      titleNorm.hashCode ^
      workKey.hashCode ^
      staves.hashCode ^
      keyFifths.hashCode ^
      timeSig.hashCode ^
      measureCount.hashCode ^
      noteCount.hashCode ^
      instrument.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScoreSummary &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          composer == other.composer &&
          titleNorm == other.titleNorm &&
          workKey == other.workKey &&
          staves == other.staves &&
          keyFifths == other.keyFifths &&
          timeSig == other.timeSig &&
          measureCount == other.measureCount &&
          noteCount == other.noteCount &&
          instrument == other.instrument;
}

/// Stem direction.
enum StemDir { up, down }

/// One staff line of music: the measure indices it contains, in order, plus the
/// staff count so a grand staff lays out together.
class System {
  final Uint32List measures;
  final int staves;

  const System({required this.measures, required this.staves});

  @override
  int get hashCode => measures.hashCode ^ staves.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is System &&
          runtimeType == other.runtimeType &&
          measures == other.measures &&
          staves == other.staves;
}

/// A time signature, e.g. 3/4 → `beats = 3`, `beat_type = 4`.
class TimeSignature {
  final int beats;
  final int beatType;

  const TimeSignature({required this.beats, required this.beatType});

  @override
  int get hashCode => beats.hashCode ^ beatType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimeSignature &&
          runtimeType == other.runtimeType &&
          beats == other.beats &&
          beatType == other.beatType;
}

/// Tuplet ratio from `time-modification` — e.g. a triplet is `3:2`.
class Tuplet {
  final int actual;
  final int normal;

  const Tuplet({required this.actual, required this.normal});

  @override
  int get hashCode => actual.hashCode ^ normal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Tuplet &&
          runtimeType == other.runtimeType &&
          actual == other.actual &&
          normal == other.normal;
}

/// A percussion note's written staff position and resolved sound.
class Unpitched {
  /// `display-step`: the written staff placement's diatonic step (A–G).
  final String displayStep;

  /// `display-octave`: the written staff placement's octave.
  final int displayOctave;

  /// The General MIDI percussion number (0-based, 35–81 for the standard
  /// kit) resolved from the part-list instrument table at parse time.
  /// `None` when the note's instrument could not be resolved; a consumer
  /// must omit such a note rather than fabricate a number.
  final int? gmNumber;

  /// The engraved head class derived beside the number (change:
  /// add-drum-notation-render) — the painters consume it verbatim.
  final HeadClass headClass;

  const Unpitched({
    required this.displayStep,
    required this.displayOctave,
    this.gmNumber,
    required this.headClass,
  });

  @override
  int get hashCode =>
      displayStep.hashCode ^
      displayOctave.hashCode ^
      gmNumber.hashCode ^
      headClass.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Unpitched &&
          runtimeType == other.runtimeType &&
          displayStep == other.displayStep &&
          displayOctave == other.displayOctave &&
          gmNumber == other.gmNumber &&
          headClass == other.headClass;
}

/// Client-side validation outcome: on success the parsed [`ScoreSummary`]; on
/// failure a stable reject `code` (`too_large` / `undecodable` / `unparseable` /
/// `no_notes`). Exactly one field is set.
class ValidationOutcome {
  final ScoreSummary? summary;
  final String? rejectCode;

  const ValidationOutcome({this.summary, this.rejectCode});

  @override
  int get hashCode => summary.hashCode ^ rejectCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ValidationOutcome &&
          runtimeType == other.runtimeType &&
          summary == other.summary &&
          rejectCode == other.rejectCode;
}
