// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'musicxml.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Parses an uncompressed MusicXML document (bytes) into a [`ScoreDocument`],
/// with each measure's `min_width` already computed. Returns an error on
/// malformed input rather than panicking.
Future<ScoreDocument> parseMusicxml({required List<int> bytes}) =>
    RustLib.instance.api.crateApiMusicxmlParseMusicxml(bytes: bytes);

/// Lays the document's measures out into [`System`]s for the given available
/// width (pixels), keeping measure order and the grand staff together.
List<System> layoutSystems({
  required ScoreDocument doc,
  required double availableWidth,
}) => RustLib.instance.api.crateApiMusicxmlLayoutSystems(
  doc: doc,
  availableWidth: availableWidth,
);

/// Starting musical attributes of the part (most-recent values win).
class Attributes {
  /// Divisions (ticks) per quarter note — the unit for every `duration`.
  final int divisions;

  /// One clef per staff, identified by clef `number`.
  final List<Clef> clefs;

  /// Key signature, in fifths on the circle (negative = flats).
  final int keyFifths;
  final TimeSignature time;

  const Attributes({
    required this.divisions,
    required this.clefs,
    required this.keyFifths,
    required this.time,
  });

  @override
  int get hashCode =>
      divisions.hashCode ^ clefs.hashCode ^ keyFifths.hashCode ^ time.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Attributes &&
          runtimeType == other.runtimeType &&
          divisions == other.divisions &&
          clefs == other.clefs &&
          keyFifths == other.keyFifths &&
          time == other.time;
}

/// Beam state at a note within a beam group.
enum BeamState { begin, continue_, end }

/// A clef on one staff: e.g. treble = `G`/2 on staff 1, bass = `F`/4 on staff 2.
class Clef {
  final int staff;
  final String sign;
  final int line;

  const Clef({required this.staff, required this.sign, required this.line});

  @override
  int get hashCode => staff.hashCode ^ sign.hashCode ^ line.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Clef &&
          runtimeType == other.runtimeType &&
          staff == other.staff &&
          sign == other.sign &&
          line == other.line;
}

/// A measure direction (expression/tempo) anchored at a staff and time position.
class Direction {
  final int staff;
  final int positionDivisions;
  final DirectionKind kind;

  const Direction({
    required this.staff,
    required this.positionDivisions,
    required this.kind,
  });

  @override
  int get hashCode =>
      staff.hashCode ^ positionDivisions.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Direction &&
          runtimeType == other.runtimeType &&
          staff == other.staff &&
          positionDivisions == other.positionDivisions &&
          kind == other.kind;
}

@freezed
sealed class DirectionKind with _$DirectionKind {
  const DirectionKind._();

  /// Free expression/tempo text (e.g. "Andantino", "dolce").
  const factory DirectionKind.words(String field0) = DirectionKind_Words;

  /// A dynamics marking (e.g. "pp", "f").
  const factory DirectionKind.dynamics(String field0) = DirectionKind_Dynamics;

  /// A hairpin: `crescendo` true = opening (<), false = diminuendo (>).
  /// `stop` marks the end of a previously opened hairpin.
  const factory DirectionKind.wedge({
    required bool crescendo,
    required bool stop,
  }) = DirectionKind_Wedge;

  /// A metronome mark, e.g. quarter = 120.
  const factory DirectionKind.metronome({
    required String beatUnit,
    required int perMinute,
  }) = DirectionKind_Metronome;
}

/// A lyric syllable attached to a note.
class Lyric {
  final String? syllabic;
  final String text;

  const Lyric({this.syllabic, required this.text});

  @override
  int get hashCode => syllabic.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Lyric &&
          runtimeType == other.runtimeType &&
          syllabic == other.syllabic &&
          text == other.text;
}

/// A measure: its notes and directions in document order, plus the engraving
/// minimum width computed from note density.
class NotationMeasure {
  /// 0-based position in the part.
  final int index;
  final List<NoteEvent> notes;
  final List<Direction> directions;

  /// Clef changes declared in this measure (empty when unchanged), so the
  /// renderer can switch clefs mid-piece (e.g. a left hand that starts in
  /// treble and moves to bass).
  final List<Clef> clefs;

  /// Minimum engraving width (pixels) from the non-linear spacing function.
  final double minWidth;

  const NotationMeasure({
    required this.index,
    required this.notes,
    required this.directions,
    required this.clefs,
    required this.minWidth,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      notes.hashCode ^
      directions.hashCode ^
      clefs.hashCode ^
      minWidth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotationMeasure &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          notes == other.notes &&
          directions == other.directions &&
          clefs == other.clefs &&
          minWidth == other.minWidth;
}

/// A single note (or rest) event.
class NoteEvent {
  final int staff;
  final int voice;

  /// Running time position within the measure (set via backup/forward), so
  /// notes on different staves/voices at the same beat share a column.
  final int positionDivisions;

  /// Pitch, or `None` for a rest.
  final Pitch? pitch;
  final bool isRest;

  /// True when this note carries `<chord/>` (sounds with the preceding note).
  final bool isChord;
  final int durationDivisions;

  /// Note-type token when present (e.g. "quarter", "eighth").
  final String? noteType;
  final int dots;

  /// Accidental token when present (e.g. "flat", "sharp", "natural").
  final String? accidental;
  final bool tieStart;
  final bool tieStop;

  /// Phrasing slur start/stop (legato arc spanning several notes).
  final bool slurStart;
  final bool slurStop;
  final Tuplet? tuplet;
  final StemDir? stem;
  final List<BeamState> beams;
  final Lyric? lyric;

  const NoteEvent({
    required this.staff,
    required this.voice,
    required this.positionDivisions,
    this.pitch,
    required this.isRest,
    required this.isChord,
    required this.durationDivisions,
    this.noteType,
    required this.dots,
    this.accidental,
    required this.tieStart,
    required this.tieStop,
    required this.slurStart,
    required this.slurStop,
    this.tuplet,
    this.stem,
    required this.beams,
    this.lyric,
  });

  @override
  int get hashCode =>
      staff.hashCode ^
      voice.hashCode ^
      positionDivisions.hashCode ^
      pitch.hashCode ^
      isRest.hashCode ^
      isChord.hashCode ^
      durationDivisions.hashCode ^
      noteType.hashCode ^
      dots.hashCode ^
      accidental.hashCode ^
      tieStart.hashCode ^
      tieStop.hashCode ^
      slurStart.hashCode ^
      slurStop.hashCode ^
      tuplet.hashCode ^
      stem.hashCode ^
      beams.hashCode ^
      lyric.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteEvent &&
          runtimeType == other.runtimeType &&
          staff == other.staff &&
          voice == other.voice &&
          positionDivisions == other.positionDivisions &&
          pitch == other.pitch &&
          isRest == other.isRest &&
          isChord == other.isChord &&
          durationDivisions == other.durationDivisions &&
          noteType == other.noteType &&
          dots == other.dots &&
          accidental == other.accidental &&
          tieStart == other.tieStart &&
          tieStop == other.tieStop &&
          slurStart == other.slurStart &&
          slurStop == other.slurStop &&
          tuplet == other.tuplet &&
          stem == other.stem &&
          beams == other.beams &&
          lyric == other.lyric;
}

/// A pitch: diatonic step, octave, and chromatic alteration (semitones).
class Pitch {
  final String step;
  final int octave;
  final int alter;

  const Pitch({required this.step, required this.octave, required this.alter});

  @override
  int get hashCode => step.hashCode ^ octave.hashCode ^ alter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Pitch &&
          runtimeType == other.runtimeType &&
          step == other.step &&
          octave == other.octave &&
          alter == other.alter;
}

/// A parsed MusicXML document: metadata, staff count, starting attributes, and
/// the ordered measures with their notes, directions, and computed geometry.
class ScoreDocument {
  final ScoreMeta meta;

  /// Number of staves in the (single) part — e.g. 2 for a piano grand staff.
  final int staves;
  final Attributes attributes;
  final List<NotationMeasure> measures;

  const ScoreDocument({
    required this.meta,
    required this.staves,
    required this.attributes,
    required this.measures,
  });

  @override
  int get hashCode =>
      meta.hashCode ^ staves.hashCode ^ attributes.hashCode ^ measures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScoreDocument &&
          runtimeType == other.runtimeType &&
          meta == other.meta &&
          staves == other.staves &&
          attributes == other.attributes &&
          measures == other.measures;
}

/// Score metadata; fields are absent (`None`) rather than failing when missing.
class ScoreMeta {
  final String? title;
  final String? composer;

  const ScoreMeta({this.title, this.composer});

  @override
  int get hashCode => title.hashCode ^ composer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScoreMeta &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          composer == other.composer;
}

/// Stem direction.
enum StemDir { up, down }

/// One staff line of music: the measure indices it contains, in order, plus the
/// staff count so a grand staff lays out together.
class System {
  final Uint32List measures;
  final int staves;

  const System({required this.measures, required this.staves});

  @override
  int get hashCode => measures.hashCode ^ staves.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is System &&
          runtimeType == other.runtimeType &&
          measures == other.measures &&
          staves == other.staves;
}

/// A time signature, e.g. 3/4 → `beats = 3`, `beat_type = 4`.
class TimeSignature {
  final int beats;
  final int beatType;

  const TimeSignature({required this.beats, required this.beatType});

  @override
  int get hashCode => beats.hashCode ^ beatType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimeSignature &&
          runtimeType == other.runtimeType &&
          beats == other.beats &&
          beatType == other.beatType;
}

/// Tuplet ratio from `time-modification` — e.g. a triplet is `3:2`.
class Tuplet {
  final int actual;
  final int normal;

  const Tuplet({required this.actual, required this.normal});

  @override
  int get hashCode => actual.hashCode ^ normal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Tuplet &&
          runtimeType == other.runtimeType &&
          actual == other.actual &&
          normal == other.normal;
}
