// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generates a demo score: a short melody in C major over 4 measures (4/4),
/// scale up then down. Timestamps are consistent with the BPM.
Future<Score> demoScore() => RustLib.instance.api.crateApiScoreDemoScore();

/// A musical measure: a group of notes.
class Measure {
  /// Measure index (0-based).
  final int index;
  final List<Note> notes;

  const Measure({required this.index, required this.notes});

  @override
  int get hashCode => index.hashCode ^ notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Measure &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          notes == other.notes;
}

/// A note placed in time.
class Note {
  /// MIDI note number (0-127). 60 = C4 (middle C).
  final int pitch;

  /// Start of the note from the beginning of the song, in milliseconds.
  final BigInt startMs;

  /// Duration of the note, in milliseconds.
  final BigInt durationMs;

  const Note({
    required this.pitch,
    required this.startMs,
    required this.durationMs,
  });

  @override
  int get hashCode => pitch.hashCode ^ startMs.hashCode ^ durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Note &&
          runtimeType == other.runtimeType &&
          pitch == other.pitch &&
          startMs == other.startMs &&
          durationMs == other.durationMs;
}

/// The complete score.
class Score {
  /// Tempo in beats per minute.
  final int bpm;
  final List<Measure> measures;

  const Score({required this.bpm, required this.measures});

  @override
  int get hashCode => bpm.hashCode ^ measures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Score &&
          runtimeType == other.runtimeType &&
          bpm == other.bpm &&
          measures == other.measures;
}
