// Copyright 2026 NEETROF
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// Regenerates `integration_test/support/capture_courses.dart` from the course
/// corpus (change: add-store-screenshot-harness).
///
/// The store captures must show the real curriculum, but the lesson catalogue is
/// served by the backend — and a capture may not depend on a live one (design
/// D3). So the *listing* metadata (ids, units, localized titles) is transcribed
/// into a Dart constant. Run this after adding or retitling a lesson:
///
/// ```bash
/// cd apps/music && dart run tool/gen_capture_courses.dart
/// ```
library;

import 'dart:convert';
import 'dart:io';

const String _corpusDir = '../../backend/content/courses';
const String _outputPath = 'integration_test/support/capture_courses.dart';

void main() {
  final corpus =
      Directory(_corpusDir)
          .listSync()
          .whereType<File>()
          .where((f) => f.path.endsWith('.json'))
          .map((f) => jsonDecode(f.readAsStringSync()) as Map<String, dynamic>)
          .where((doc) => doc['status'] == 'published')
          .toList()
        ..sort(
          (a, b) => (a['sortOrder'] as int).compareTo(b['sortOrder'] as int),
        );

  final buffer = StringBuffer(_header);
  for (final doc in corpus) {
    buffer
      ..writeln('  CourseListing(')
      ..writeln("    id: ${_dart(doc['id'] as String)},")
      ..writeln("    schemaVersion: ${doc['schemaVersion']},")
      ..writeln("    track: ${_dart(doc['track'] as String)},")
      ..writeln("    level: ${_dart(doc['level'] as String)},")
      ..writeln("    unit: ${_dart(doc['unit'] as String)},")
      ..writeln("    unitTitle: ${_inline(doc['unitTitle'])},")
      ..writeln("    sortOrder: ${doc['sortOrder']},")
      ..writeln("    title: ${_inline(doc['title'])},")
      ..writeln('  ),');
  }
  buffer.writeln('];');

  File(_outputPath).writeAsStringSync(buffer.toString());
  stdout.writeln('wrote $_outputPath (${corpus.length} lessons)');
}

/// A localized map literal, locales in a stable order so a regeneration only
/// diffs where the corpus actually changed.
String _inline(Object? value) {
  final map = (value as Map).cast<String, dynamic>();
  const order = ['en', 'fr', 'it', 'es'];
  final entries = [
    for (final code in order)
      if (map[code] case final String text) "'$code': ${_dart(text)}",
  ];
  return '{${entries.join(', ')}}';
}

/// [text] as a single-quoted Dart literal.
String _dart(String text) {
  final escaped = text
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$');
  return "'$escaped'";
}

const String _header = '''
// Copyright 2026 NEETROF
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// GENERATED by `dart run tool/gen_capture_courses.dart` from
// backend/content/courses/. Do not edit by hand.

/// The solfège curriculum as the store captures show it (change:
/// add-store-screenshot-harness): the listing metadata of the published lessons
/// under `backend/content/courses/`, transcribed here so the capture scenario
/// renders the REAL curriculum without a backend — the corpus is served by the
/// server, and a capture must never depend on whatever a database holds
/// (design D3).
///
/// Titles travel with their four shipping locales, so one fixture serves every
/// locale run: the widgets resolve the language themselves.
library;

import 'package:music/courses/course_manifest.dart';

/// Every published lesson, in catalogue order.
const List<CourseListing> kCaptureCourses = [
''';
